force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>81</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Alpha2Code__c</fullName>
    <label>Country Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Alpha3Code__c</fullName>
    <label>Country Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Capital__c.field-meta.xml
<CustomField>
    <fullName>Country_Capital__c</fullName>
    <label>Country Capital</label>
    <length>81</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Region__c.field-meta.xml
<CustomField>
    <fullName>Country_Region__c</fullName>
    <label>Country Region</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetCountryFieldsOnLead.cls
/**
 * @Author       : Mohammad Arafat Ali
 * @Description  : Apex class to get country fields on Lead Object.
 * @Date         : 05-20-2025
**/

public class GetCountryFieldsOnLead {
    public static void getCountryFields(List<Country__c> countryList) {
        try{
            List<Lead> leadToUpdate = new List<Lead>();
            Map<Id,Country__c> mapOfCountryIdVsCountry = new Map<Id,Country__c>();

            for (Country__c c : countryList) {
                mapOfCountryIdVsCountry.put(c.Id, c);
            }

            for (Lead l : [SELECT Id, Name, Country__c, Country_Alpha2Code__c, Country_Alpha3Code__c, Country_Capital__c, Country_Region__c 
                            FROM Lead 
                            WHERE Country__c IN :mapOfCountryIdVsCountry.keyset()]
                            ) {
                if(mapOfCountryIdVsCountry.containsKey(l.Country__c)){
                    l.Country__c = mapOfCountryIdVsCountry.get(l.Country__c).Id;
                    l.Country_Alpha2Code__c = mapOfCountryIdVsCountry.get(l.Country__c).Alpha2Code__c;
                    l.Country_Alpha3Code__c = mapOfCountryIdVsCountry.get(l.Country__c).Alpha3Code__c;
                    l.Country_Capital__c = mapOfCountryIdVsCountry.get(l.Country__c).Capital_City__c;
                    l.Country_Region__c = mapOfCountryIdVsCountry.get(l.Country__c).Region__c;
                    leadToUpdate.add(l);
                }
            }
            if(!leadToUpdate.isEmpty()){
                update leadToUpdate;
            }
        }catch(Exception e){
            //log exception
            System.debug('=== Error updating leads ==='+e.getMessage());
        }
    }
}